# Generated by Django 3.2.13 on 2022-07-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.PositiveIntegerField()),
                ('natural_gas', models.PositiveIntegerField()),
                ('fuel_oil', models.PositiveIntegerField()),
                ('LPG', models.PositiveIntegerField()),
                ('waste', models.PositiveIntegerField()),
                ('water', models.PositiveIntegerField()),
                ('vehicle', models.PositiveIntegerField()),
                ('bus', models.PositiveIntegerField()),
                ('metro', models.PositiveIntegerField()),
                ('taxi', models.PositiveIntegerField()),
                ('rail', models.PositiveIntegerField()),
                ('flying', models.PositiveIntegerField()),
                ('red_meat', models.PositiveIntegerField()),
                ('white_meat', models.PositiveIntegerField()),
                ('dairy', models.PositiveIntegerField()),
                ('cereals', models.PositiveIntegerField()),
                ('vegetables', models.PositiveIntegerField()),
                ('oils', models.PositiveIntegerField()),
                ('fruit', models.PositiveIntegerField()),
                ('snacks', models.PositiveIntegerField()),
                ('drinks', models.PositiveIntegerField()),
            ],
        ),
    ]
