from django.db import models

class Calculation_Input(models.Model):
    electricity = models.PositiveIntegerField()
    natural_gas = models.PositiveIntegerField()
    fuel_oil = models.PositiveIntegerField()
    LPG = models.PositiveIntegerField()
    waste = models.PositiveIntegerField()
    water = models.PositiveIntegerField()
    vehicle = models.PositiveIntegerField()
    bus = models.PositiveIntegerField()
    metro = models.PositiveIntegerField()
    taxi = models.PositiveIntegerField()
    rail = models.PositiveIntegerField()
    flying = models.PositiveIntegerField()
    red_meat = models.PositiveIntegerField()
    white_meat = models.PositiveIntegerField()
    dairy = models.PositiveIntegerField()
    cereals = models.PositiveIntegerField()
    vegetables = models.PositiveIntegerField()
    oils = models.PositiveIntegerField()
    fruit = models.PositiveIntegerField()
    snacks = models.PositiveIntegerField()
    drinks = models.PositiveIntegerField()
